const passages=require('./homework-3-passages.json');
const questions=[];
function add(source,subject,skill,level,group,prompt,choices,answer,explanation,diagram=null){
  questions.push({id:'B-'+source,source,subject,skill,level,difficulty:['Easy','Medium','Hard'][level],group,prompt,choices,answer,explanation,diagram,passage:passages[group]||null});
}

add(92,'Math','Percent change',1,'math','Tuesday reached 84 F, which was 5% warmer than Monday. Wednesday was 10% cooler than Monday. How many degrees cooler was Wednesday than Monday?',['4 F','8 F','8.4 F','12 F'],1,'Monday was 84 / 1.05 = 80 F. Ten percent of 80 is 8 F.');
add(93,'Math','Factors',2,'math','Three consecutive integers, n - 1, n, and n + 1, each divide 168 evenly. What is the largest possible n?',['3','6','7','14'],2,'6, 7, and 8 all divide 168. No larger consecutive triple of factors works.');
add(94,'Math','Modular arithmetic',0,'math','A concert happened 86 days after an earlier concert. The later concert was on Tuesday. What day was the earlier one?',['Sunday','Monday','Wednesday','Thursday'],0,'86 days is 12 weeks plus 2 days. Two days before Tuesday is Sunday.');
add(95,'Math','Rates',1,'math','A worker took home $213 for 20 hours after $32 in taxes. What was the hourly pay before tax?',['$9.05','$10.65','$12.25','$15.25'],2,'Gross pay was 213 + 32 = 245 dollars. Divide by 20 hours to get $12.25 per hour.');
add(96,'Math','Surface area',2,'math','The closed rectangular box shown measures 20 cm by 40 cm by 50 cm. What is its total outside surface area?',['3,800 square cm','5,600 square cm','7,600 square cm','40,000 square cm'],2,'Surface area is 2(20 x 40 + 20 x 50 + 40 x 50) = 2(800 + 1,000 + 2,000) = 7,600 square cm.',{type:'rectangular-box',caption:'Closed rectangular prism with length 50 cm, width 40 cm, and height 20 cm. Not to scale.'});
add(97,'Math','Linear change',1,'math','A car loses the same dollar value each year. It was worth $15,000 after 3 years and $10,000 after 5 years. What was its original value?',['$18,000','$20,000','$22,500','$25,000'],2,'It lost $5,000 over 2 years, or $2,500 per year. Three years earlier it was worth 15,000 + 3(2,500) = $22,500.');
add(98,'Math','Probability',2,'math','A bag has 4 blue, 2 green, and 3 yellow disks. Four disks are drawn without replacement. What is the chance that every disk drawn is blue?',['1/126','1/36','4/9','16/81'],0,'Multiply 4/9 x 3/8 x 2/7 x 1/6 = 1/126.');
add(99,'Math','Percent notation',0,'math','Which expression is NOT equal to one-half percent?',['0.005','1/200','5/1,000','0.005/100'],3,'One-half percent equals 0.5/100 = 0.005 = 1/200. Dividing 0.005 by 100 again gives 0.00005.');
add(100,'Math','Repeated percent growth',2,'math','A club started with 50 members. Membership grew 40% in each of the next 3 years. About how many members did it have after the third increase?',['70','98','120','137'],3,'Apply each increase to the new total: 50(1.4)^3 = 137.2, which rounds to 137.');
add(101,'Math','Inequalities',2,'math','Solve 6x - 20 < 5x - 2(5 - 3x).',['x < -2','x > -2','x < 16','x > 16'],1,'The right side is 11x - 10. Then -10 < 5x, so x > -2.');
add(102,'Math','Ratios and probability',1,'math','Thirty clips are red, white, and blue in a 2:5:3 ratio. One clip of each color is removed. What is the chance the next clip is blue?',['5/27','2/7','8/27','3/10'],2,'There were 9 blue clips. After removing one, 8 blue remain out of 27 clips.');
add(103,'Math','Least common multiple',1,'math','What is the smallest positive number divisible by every integer from 1 through 8?',['420','480','840','1,680'],2,'Use the highest needed prime powers: 2^3 x 3 x 5 x 7 = 840.');
add(104,'Math','Counting arrangements',0,'math','Use three different paint colors on a door, its frame, and a wall, with no color repeated. How many arrangements are possible?',['3','6','9','27'],1,'Choose among 3 colors for the door, then 2 for the frame, then 1 for the wall: 3 x 2 x 1 = 6.');
add(105,'Math','Similar triangles',2,'math','In the diagram, triangles MNP and XYZ are similar. The small triangle has equal sloping sides of 9 cm and a 6 cm base. The large triangle has a 10 cm base and equal sloping sides. What is the large triangle\'s perimeter?',['25 cm','30 cm','36 cm','40 cm'],3,'The scale factor is 10/6 = 5/3. Each large sloping side is 9(5/3) = 15 cm. Perimeter = 15 + 15 + 10 = 40 cm.',{type:'similar-triangles',caption:'Large triangle MNP: base MP = 10 cm, MN = NP. Similar small triangle XYZ: base XZ = 6 cm, XY = YZ = 9 cm. Not to scale.'});
add(106,'Math','Signs of products',2,'math','For nonzero integers w, x, y, and z, when is x^2 y z^3 |w| guaranteed to be positive?',['x and w are positive','x and w are negative','y and z are both negative','x and y are negative while z and w are positive'],2,'x^2 and |w| are positive; z^3 has the sign of z. The product is positive when y and z have the same sign. The given matching-sign condition is both negative.');
add(107,'Math','Dependent probability',1,'math','Chris has 1 red, 2 white, and 3 black shirts. He randomly picks two without putting the first back. What is P(black first, then red)?',['1/12','1/10','1/5','3/5'],1,'P(black first) = 3/6. Then P(red second) = 1/5. Their product is 1/10.');
add(108,'Math','Cube roots',0,'math','A large solid cube is built from 125 unit cubes, each with a 1-inch edge. How long is one edge of the large cube?',['5 inches','25 inches','41 2/3 inches','125 inches'],0,'Five unit cubes fit along each edge because 5 x 5 x 5 = 125.');

add(33,'English','Central idea',1,'morse','What broad idea does the section about Morse\'s developing invention emphasize?',['Turning electrical signaling into a working device took sustained study, experiments, and contributions from several people.','Morse built a complete telegraph as soon as he heard about the electromagnet.','Morse\'s college lectures gave him all the technical knowledge he needed.','Visual signaling was more reliable than sending pulses through wires.'],0,'Morse\'s early interest led to experiments, but progress also depended on Henry\'s research, Gale\'s advice, and Vail\'s technical work.');
add(34,'English','Text structure',1,'morse','Why does paragraph 3 describe Henry\'s earlier work before Gale\'s improvements to Morse\'s design?',['To show that Morse and Henry completed their telegraphs at the same time.','To show how later progress built on discoveries and methods developed by others.','To show that visual signals remained more effective than electricity.','To show that a patent mattered more than the device itself.'],1,'The sequence traces Henry\'s experiments and relay system into Gale\'s guidance and Morse\'s working design.');
add(35,'English','Summarizing',1,'morse','Which account best summarizes how Morse received money for his Washington-to-Baltimore line?',['He immediately won the Atlantic coast signaling prize in 1837.','A European patent paid for construction while Congress debated.','He requested federal funding, demonstrated the system, waited through a depression, and won congressional approval in 1843.','Gale and Vail bought the equipment after the government rejected his application.'],2,'Paragraphs 4-6 give this sequence: application and demonstration, economic delay, then approved federal funding.');
add(36,'English','Word choice',0,'morse','The account calls the completed link a dramatic success. What feeling does that wording add?',['Regret about abandoning the underground design.','Celebration and amazement that the line worked.','Fear that the system would soon fail.','Certainty that all future lines would be identical.'],1,'The words emphasize the excitement of a successful public demonstration after setbacks.');
add(37,'English','Interpreting graphs',1,'morse','How does the chart of U.S. telegraph messages strengthen the passage\'s final paragraph?',['It proves that every message was sent with the same code.','It shows message volume rising greatly as the network expanded.','It shows that visual signals continued to dominate after 1920.','It shows that operators stopped recording messages on paper in 1880.'],1,'The chart climbs from roughly 12 million messages in 1870 to roughly 155 million in 1920, evidence of greatly increased use.',{type:'telegraph-chart',caption:'U.S. telegraph messages transmitted, approximately 12, 30, 55, 67, 75, and 155 million in 1870, 1880, 1890, 1900, 1910, and 1920.'});
add(38,'English','Inference',1,'morse','Which early detail best shows that lawmakers had not yet imagined the possibilities of an electric telegraph?',['They sought a chain of flag-and-light stations along the Atlantic coast.','Morse studied rival systems while visiting Europe.','Cornell suggested overhead wire to finish the line on time.','Operators later learned to read code as it arrived.'],0,'The proposed coastal system used visual signals, showing the earlier understanding of long-distance communication.');
add(39,'English','Author perspective',2,'morse','Which claim about Morse\'s work is most consistent with the passage as a whole?',['The aboveground line mattered more than the ability to send coded messages.','Electrical knowledge was unnecessary for building his system.','The economic delay was the main reason the telegraph succeeded.','The invention helped connect people across the United States and beyond.'],3,'The final paragraph describes lines spreading westward and linking Europe and North America.');
add(40,'English','Using visuals',1,'morse','What does the 1902 network diagram add to the account of the telegraph\'s growth?',['It shows that electric links reached far beyond the earlier hill-to-hill visual systems.','It proves Morse personally built every line on the map.','It identifies the exact relay Gale recommended in 1832.','It shows North America had no telegraph connections.'],0,'The network crosses oceans and connects several continents, extending far beyond the scope of the earlier visual signaling proposal.',{type:'telegraph-network',caption:'Schematic of the 1902 British All-Red telegraph network linking North America, Europe, Africa, India, Australia, and New Zealand. Routes are simplified.'});

add(41,'English','Central idea',1,'snow','How does the first stanza present the mountains in relation to the city?',['It describes both city and mountains as equally grand.','It places majestic mountains above the dull city rooftops.','It suggests city residents built the mountains.','It says the mountains are too small to be noticed.'],1,'The mountains are compared with palaces, angels, and pillars above dingy roofs.');
add(42,'English','Figurative language',1,'snow','What does calling the mountains "pillars of the sky" suggest?',['They are fragile and likely to fall.','They are strong, lofty, and almost supportive of the sky.','They hide the sky completely from the city.','They were constructed to protect the city.'],1,'A pillar holds something up; the image lends the mountains dignity and strength.');
add(43,'English','Poetic structure',1,'snow','Why does the poet place "Uprise" alone on line 7?',['To make the city seem taller than the mountains.','To suggest the mountains have vanished.','To introduce a new speaker.','To emphasize the mountains\' commanding rise over the landscape.'],3,'The isolated verb visually and rhythmically stresses their ascent.');
add(44,'English','Textual evidence',0,'snow','Which line most directly shows people using mountain scenery for commercial gain?',['"Above the dingy city-roofs" (line 3)','"The world makes war on them" (line 10)','"Tunnels their granite cliffs" (line 11)','"Plasters their cliffs with soap-advertisements" (line 13)'],3,'The advertisements use the cliffs as a place to promote products.');
add(45,'English','Speaker perspective',1,'snow','What attitude toward human activity is clearest in the second stanza?',['Admiration for mountain engineering.','Indifference to changes in the landscape.','Criticism of careless damage to the natural setting.','Confidence that advertising helps people appreciate mountains.'],2,'The stanza says people make war on, split, plaster, and destroy the mountains\' peace.');
add(46,'English','Inference',0,'snow','Which line suggests that familiarity causes people to overlook the mountains?',['"The mountains from the great plateau" (line 6)','"They have been here now for too long a time" (line 9)','"Splits down their shining sides" (line 12)','"To which the future is as was the past" (line 18)'],1,'The speaker links the world\'s failure to heed the mountains with how long they have been present.');
add(47,'English','Speaker perspective',2,'snow','What troubles the speaker in lines 21-22 about people who break through the mountains?',['They cannot find a path across the plateau.','They have too little time to study the rocks.','They damage a landscape whose enduring beauty they do not value.','They believe the mountains will never change.'],2,'The speaker says the people who break the barrier do not need the joy of the old, weathered stone.');
add(48,'English','Theme',2,'snow','How does the last stanza develop the poem\'s theme?',['It emphasizes the mountains\' lasting, untamed presence despite human interference.','It shows that people can fully control the landscape.','It argues that the mountains exist mainly to support commerce.','It shows that the mountains are becoming part of the city.'],0,'Images of repeated peaks, wilderness, long time, and a broad horizon stress nature\'s endurance.');
add(49,'English','Personification',1,'snow','In the final four lines, the mountains appear to welcome the mists. What does this personification suggest?',['They are gracious hosts, seemingly undisturbed by people\'s actions.','They are performers seeking the city\'s applause.','They are unaware that mist may harm them.','They are embarrassed by the passing clouds.'],0,'The welcoming gesture makes the mountains seem generous and calm, in contrast with the human damage described earlier.');

module.exports={title:'Homework Quiz #3',version:'homework-3-form-b-v1',questions,passages,counts:{Math:17,English:17},groups:['math','morse','snow']};
